version: '3.9'

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: <db_name>
      MYSQL_ROOT_PASSWORD: <db_root_password>
      MYSQL_USER: <db_user>
      MYSQL_PASSWORD: <db_password>
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sail

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: <db_root_password>
    networks:
      - sail
    ports:
      - 8001:80
